"""add avatar_emoji and theme to student

Revision ID: 8f50716ce9b2
Revises: 
Create Date: 2025-07-01 15:55:48.112741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f50716ce9b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('avatar_emoji', sa.String(), nullable=True))
    op.add_column('students', sa.Column('theme', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'theme')
    op.drop_column('students', 'avatar_emoji')
    # ### end Alembic commands ###
